# 测试配置文件
api:
  openai_api_key: "test-key"
  openai_base_url: "http://localhost:11434/v1"
  timeout: 30

models:
  embedding:
    name: "text-embedding-3-small"
    dim: 1536
    batch_size: 100
  llm:
    name: "gpt-3.5-turbo"
    temperature: 0.7
    top_p: 1.0
    top_k: 40
    max_tokens: 1000
    stop: []
    system_prompt: "你是一个专业的AI助手，请基于提供的上下文信息准确回答问题。"

database:
  host: "localhost"
  port: 19530
  collection_name: "test_rag"
  embedding_dim: 1536
  metric_type: "COSINE"
  index_type: "IVF_FLAT"
  nlist: 1024
  consistency_level: "Strong"
  batch_size: 1000

data:
  data_path_glob: "milvus_docs/en/faq/*.md"
  file_extensions: [".md", ".txt"]
  chunk_size: 1000
  chunk_overlap: 200
  chunk_strategy: "semantic"

search:
  search_limit: 10
  use_reranker: true
  rerank_top_k: 5
  rerank_algorithm: "hybrid"

logging:
  log_level: "INFO"
  log_file: "logs/test.log" 